version: "3.9"
services:
  vscode:
    image: "mcr.microsoft.com/vscode/devcontainers/base"
    volumes:
      - ..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
  structurizr:
    image: "structurizr/lite"
    ports:
      - "8080:8080"
    volumes:
      - ..:/usr/local/structurizr:cached
